///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RxDemoApp.レコーディングモジュール.Introduction
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 名前の登録 recording.
    /// </summary>
    [TestModule("a710d971-275b-4530-8c12-d13a6aee11f9", ModuleType.Recording, 1)]
    public partial class 名前の登録 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RxDemoApp.RxDemoAppRepository repository.
        /// </summary>
        public static global::RxDemoApp.RxDemoAppRepository repo = global::RxDemoApp.RxDemoAppRepository.Instance;

        static 名前の登録 instance = new 名前の登録();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 名前の登録()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 名前の登録 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RxTabIntroduction.EnterYourName' at 131;12.", repo.ApplicationUnderTest.RxTabIntroduction.EnterYourNameInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.RxTabIntroduction.EnterYourName.Click("131;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Taro' with focus on 'ApplicationUnderTest.RxTabIntroduction.EnterYourName'.", repo.ApplicationUnderTest.RxTabIntroduction.EnterYourNameInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.RxTabIntroduction.EnterYourName.PressKeys("Taro");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RxTabIntroduction.BtnSubmitUserName' at 24;11.", repo.ApplicationUnderTest.RxTabIntroduction.BtnSubmitUserNameInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.RxTabIntroduction.BtnSubmitUserName.Click("24;11");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
