///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RxDemoApp.レコーディングモジュール.Introduction
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 登録画面の検証 recording.
    /// </summary>
    [TestModule("1f2d0e44-ff32-4420-a7c2-405703d7b1a0", ModuleType.Recording, 1)]
    public partial class 登録画面の検証 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RxDemoApp.RxDemoAppRepository repository.
        /// </summary>
        public static global::RxDemoApp.RxDemoAppRepository repo = global::RxDemoApp.RxDemoAppRepository.Instance;

        static 登録画面の検証 instance = new 登録画面の検証();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 登録画面の検証()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 登録画面の検証 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Welcome, Taro!') on item 'ApplicationUnderTest.RxTabIntroduction.LblWelcomeMessage'.", repo.ApplicationUnderTest.RxTabIntroduction.LblWelcomeMessageInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.ApplicationUnderTest.RxTabIntroduction.LblWelcomeMessageInfo, "Text", "Welcome, Taro!");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
