///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RxDemoApp.レコーディングモジュール.TestDatabase
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The エントリーの登録 recording.
    /// </summary>
    [TestModule("c36c2649-b97f-4570-8dc3-41e020c65ff4", ModuleType.Recording, 1)]
    public partial class エントリーの登録 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RxDemoApp.RxDemoAppRepository repository.
        /// </summary>
        public static global::RxDemoApp.RxDemoAppRepository repo = global::RxDemoApp.RxDemoAppRepository.Instance;

        static エントリーの登録 instance = new エントリーの登録();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public エントリーの登録()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static エントリーの登録 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RxTabStandard.FirstName' at 131;14.", repo.ApplicationUnderTest.RxTabStandard.FirstNameInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.RxTabStandard.FirstName.Click("131;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Taro' with focus on 'ApplicationUnderTest.RxTabStandard.FirstName'.", repo.ApplicationUnderTest.RxTabStandard.FirstNameInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.RxTabStandard.FirstName.PressKeys("Taro");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RxTabStandard.Button開く' at 4;15.", repo.ApplicationUnderTest.RxTabStandard.Button開くInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.RxTabStandard.Button開く.Click("4;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.ProjectManagement' at 254;11.", repo.List1000.ProjectManagementInfo, new RecordItemIndex(3));
            repo.List1000.ProjectManagement.Click("254;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RxTabStandard.UpDownEdit' at 68;15.", repo.ApplicationUnderTest.RxTabStandard.UpDownEditInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.RxTabStandard.UpDownEdit.Click("68;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}30' with focus on 'ApplicationUnderTest.RxTabStandard.UpDownEdit'.", repo.ApplicationUnderTest.RxTabStandard.UpDownEditInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.RxTabStandard.UpDownEdit.PressKeys("{Back}30");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RxTabStandard.RdbMale' at 6;14.", repo.ApplicationUnderTest.RxTabStandard.RdbMaleInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.RxTabStandard.RdbMale.Click("6;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RxTabStandard.BtnAddPerson' at 45;10.", repo.ApplicationUnderTest.RxTabStandard.BtnAddPersonInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.RxTabStandard.BtnAddPerson.Click("45;10");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
