///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RxDemoApp.レコーディングモジュール.TestDatabase
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The エントリーの削除 recording.
    /// </summary>
    [TestModule("4568afc3-fcf6-4e26-a9f5-9a91299aef89", ModuleType.Recording, 1)]
    public partial class エントリーの削除 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RxDemoApp.RxDemoAppRepository repository.
        /// </summary>
        public static global::RxDemoApp.RxDemoAppRepository repo = global::RxDemoApp.RxDemoAppRepository.Instance;

        static エントリーの削除 instance = new エントリーの削除();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public エントリーの削除()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static エントリーの削除 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RxTabStandard.TaroMale30ProjectManagement' at 70;7.", repo.ApplicationUnderTest.RxTabStandard.TaroMale30ProjectManagementInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.RxTabStandard.TaroMale30ProjectManagement.Click("70;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RxTabStandard.BtnDeletePerson' at 48;14.", repo.ApplicationUnderTest.RxTabStandard.BtnDeletePersonInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.RxTabStandard.BtnDeletePerson.Click("48;14");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
