///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RxDemoApp.レコーディングモジュール.TestDatabase
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The データベース画面の表示 recording.
    /// </summary>
    [TestModule("b151f15d-b6b0-49ea-a07b-3347e8e06883", ModuleType.Recording, 1)]
    public partial class データベース画面の表示 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RxDemoApp.RxDemoAppRepository repository.
        /// </summary>
        public static global::RxDemoApp.RxDemoAppRepository repo = global::RxDemoApp.RxDemoAppRepository.Instance;

        static データベース画面の表示 instance = new データベース画面の表示();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public データベース画面の表示()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static データベース画面の表示 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TestDatabase' at 54;2.", repo.ApplicationUnderTest.TestDatabaseInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.TestDatabase.Click("54;2");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
